const fs = require('fs');
const path = require('path');

function parseEnvContent(content) {
  return content.split('\n').reduce((acc, line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      return acc;
    }

    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      acc[match[1].trim()] = match[2].trim();
    }

    return acc;
  }, {});
}

function loadEnvFromFile(envFilePath) {
  try {
    const content = fs.readFileSync(path.resolve(__dirname, '..', envFilePath), 'utf8');
    return parseEnvContent(content);
  } catch {
    return null;
  }
}

function isProductionBuild() {
  return (
    process.argv.includes('--production') ||
    process.env.NODE_ENV === 'production' ||
    process.env.VERCEL === '1'
  );
}

function resolveEnvVars() {
  const production = isProductionBuild();
  const envFile = production ? '.env.production' : '.env.development';
  const fileVars = loadEnvFromFile(envFile) ?? {};

  const apiUrl = process.env.API_URL || fileVars.API_URL || (production ? '' : '/api/v1');
  const locationId = process.env.LOCATION_ID || fileVars.LOCATION_ID || '';

  let source = 'default';
  if (process.env.API_URL || process.env.LOCATION_ID) {
    source = 'process.env';
  } else if (fileVars.API_URL || fileVars.LOCATION_ID) {
    source = envFile;
  }

  return { production, apiUrl, locationId, source, envFile };
}

function generateEnvFile(outputFilePath) {
  const { production, apiUrl, locationId, source, envFile } = resolveEnvVars();

  if (!apiUrl) {
    console.error(
      `Error: API_URL is required for production builds. Set it in ${envFile} or as an environment variable.`,
    );
    process.exit(1);
  }

  const envSourceLabel = production ? '.env.production' : '.env.development';
  const fileContent = `/**
 * THIS FILE IS AUTO-GENERATED BY scripts/generate-env.js
 * DO NOT EDIT MANUALLY. Update ${envSourceLabel} or environment variables.
 */
export const ENV = {
  production: ${production},
  apiUrl: '${apiUrl}',
  locationId: '${locationId}'
};
`;

  const dir = path.dirname(outputFilePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputFilePath, fileContent, 'utf8');
  console.log(`Generated ${outputFilePath} (${production ? 'production' : 'development'}, source: ${source})`);
}

const outputPath = path.resolve(__dirname, '../src/app/core/config/env.config.ts');
generateEnvFile(outputPath);
